
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unoujpmnyfcwuldjnmmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVub3VqcG1ueWZjd3VsZGpubW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjQzMDUsImV4cCI6MjA2MTA0MDMwNX0.ZbkKeFpf-jJdSYlMrbRhQsjSC1g3D-WJ6XlzjhxAcTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
