// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujmqynrolttckwwschvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbXF5bnJvbHR0Y2t3d3NjaHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDk4NDYsImV4cCI6MjA1OTI4NTg0Nn0.7OAZbtNft1DEgKgekZMq6F0F-PlJ7uZMBA4Sy7jURLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);